<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>

        <PackageId>EasyOpenVR</PackageId>
        <Authors>BOLL7708</Authors>
        <Description>This is a Class Library to make it easier to talk to the OpenVR API using the official C# headers</Description>
        <PackageTags>openvr steamvr openvr-api</PackageTags>
        <PackageProjectUrl>https://github.com/BOLL7708/EasyOpenVR</PackageProjectUrl>
        <RepositoryUrl>https://github.com/BOLL7708/EasyOpenVR</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Update="openvr_api.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="LICENSE.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
